version: '3'
services:
 fast_ai:
  networks:
   fast_ai:
    ipv4_address: 10.0.11.43
  build: .
  ports:
   - "8888:8888"
  volumes:
   - /code/hittudiv/courses:/opt/courses
   - /Users/hittu/.keras:/root/.keras

networks:
  fast_ai:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.11.0/16

